baseURL = deborareis.net.br
title = "Débora Reis"
theme = "hugo-coder"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
enableEmoji = true
#relativeURLs = true
#canonifyURLs = true

[pagination]
pagerSize = 6

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Débora Reis"
description = "Portfólio de Débora Reis"
keywords = "blog,segurança,pessoal"
info = ["Especialista em Cibersegurança"]
avatarURL = "images/debora.png"
#gravatar = "consultoria.deborareis@gmail.com"
dateFormat = "Setembro 29, 2025"
since = "2025"
rtl = false
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
author = "debora"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/deboranreis"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/debora-reis/"

[languages.pt-br]
languageName = ":brazil:"

[languages.pt-br.params]
author = "Débora Reis"
info = "Especialista de Cibersegurança"
description = "Portfólio de Débora Reis"


[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "/sobre/"

[[languages.pt-br.menu.main]]
name = "Blog"
weight = 2
url = "/blog/"

[[languages.pt-br.menu.main]]
name = "Serviços"
weight = 3
url = "/servicos/"

[[languages.pt-br.menu.main]]
name = "Contato"
weight = 5
url = "/contato/"